name: CI

on: [push, pull_request]

env:
  SDL2_VERSION: 2.30.11

jobs:
  linux:
    name: Steam Linux Runtime
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate glimp files
      run: ./flibitGLIMP.sh

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: |
        ninja -C release
        strip -S release/qc
        mv release/qc qc.bin.x86_64

    - name: CMake configure (Release 32-bit)
      run: CC="cc -m32" CXX="c++ -m32" cmake -B release32 -G Ninja . -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release 32-bit)
      run: |
        ninja -C release32
        strip -S release32/qc
        mv release32/qc qc.bin.x86

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: qc-linux
        path: qc.bin.*

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate glimp files
      run: ./flibitGLIMP.sh

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

    - name: Build (Release)
      run: |
        ninja -C release
        strip -S release/qc
        mv release/qc "Quadrilateral Cowboy"

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: qc-osx
        path: "Quadrilateral Cowboy"

  windows:
    name: Win32
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: CMake configure (Debug)
      run: cmake -B debug -G "Visual Studio 17 2022" . -A Win32 -DCMAKE_BUILD_TYPE=Debug

    - name: Build (Debug)
      run: cmake --build debug --config Debug

    - name: CMake configure (Release)
      run: cmake -B release -G "Visual Studio 17 2022" . -A Win32 -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: |
        cmake --build release --config Release

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: qc-win32
        path: release/Release/qc.exe
