name: CI

on: [push, pull_request]

env:
  SDL2_VERSION: 2.30.11

jobs:
  linux:
    name: Steam Linux Runtime
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate glimp files
      run: ./flibitGLIMP.sh

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: |
        ninja -C release

  macos:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate glimp files
      run: ./flibitGLIMP.sh

    - name: Install dependencies
      run: brew install sdl2

    - name: CMake configure (Debug)
      run: cmake -B debug -G Ninja . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

    - name: Build (Debug)
      run: ninja -C debug

    - name: CMake configure (Release)
      run: cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

    - name: Build (Release)
      run: ninja -C release
